CREATE DATABASE genes;

CREATE TABLE corr
(
  mrna varchar(30) NOT NULL,
  mirna varchar(30) NOT NULL,
  corr DOUBLE NOT NULL,
  target_profiler BOOLEAN,
  target_scan BOOLEAN,
  target_miranda BOOLEAN,
  db_num INTEGER NOT NULL
);

LOAD DATA LOCAL INFILE '~/Downloads/Data/original.txt' INTO TABLE corr
FIELDS TERMINATED BY '\t'
LINES TERMINATED BY '\n'
IGNORE 1 lines;

UPDATE corr SET db_num = target_profiler + target_scan + target_miranda; 

SELECT mrna, mirna, corr, db_num FROM corr 
WHERE corr != 1000000 AND db_num != 0
INTO OUTFILE '/usr/local/dbOutput/refined.csv'
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n';

SELECT mrna, mirna, corr, db_num FROM corr 
WHERE corr != 1000000 AND db_num != 0
LIMIT 30000
INTO OUTFILE '/usr/local/dbOutput/refined.csv'
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n';

CREATE TABLE mrna_expr 
(
  gene varchar(30) NOT NULL, 
  UNCID_846282_TCGA_BL_A0C8_01 DOUBLE,
  UNCID_846160_TCGA_BL_A13J_01 DOUBLE,
  UNCID_846155_TCGA_BL_A13J_11 DOUBLE,
  UNCID_843720_TCGA_BT_A0S7_01 DOUBLE,
  UNCID_844379_TCGA_BT_A0YX_01A_11 DOUBLE,
  UNCID_843703_TCGA_C4_A0F0_01 DOUBLE,
  UNCID_843691_TCGA_C4_A0F6_01 DOUBLE,
  UNCID_844369_TCGA_CU_A0YN_01 DOUBLE,
  UNCID_843582_TCGA_CU_A0YN_11 DOUBLE,
  UNCID_844308_TCGA_CU_A0YO_01 DOUBLE,
  UNCID_844312_TCGA_CU_A0YR_01 DOUBLE,
  UNCID_843475_TCGA_CU_A0YR_11 DOUBLE,
  average DOUBLE
);

LOAD DATA LOCAL INFILE '~/Downloads/Data/expression/mrna.csv' INTO TABLE mrna_expr
FIELDS TERMINATED BY ',' 
LINES TERMINATED BY '\n' 
IGNORE 1 LINES;

SELECT gene, average FROM mrna_expr
INTO OUTFILE '/usr/local/dbOutput/mrna.csv'
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n';

CREATE TABLE mirna_expr 
(
  id varchar(30) NOT NULL, 
  TCGA_BL_A0C8_01 DOUBLE,
  TCGA_BL_A13J_01 DOUBLE,
  TCGA_BL_A13J_11 DOUBLE,
  TCGA_BT_A0S7_01 DOUBLE,
  TCGA_BT_A0YX_01 DOUBLE,
  TCGA_C4_A0F0_01 DOUBLE,
  TCGA_C4_A0F6_01 DOUBLE,
  TCGA_CU_A0YN_01 DOUBLE,
  TCGA_CU_A0YN_11 DOUBLE,
  TCGA_CU_A0YO_01 DOUBLE,
  TCGA_CU_A0YR_01 DOUBLE,
  TCGA_CU_A0YR_11 DOUBLE,
  average DOUBLE
);

LOAD DATA LOCAL INFILE '~/Downloads/Data/expression/mirna.csv' INTO TABLE mirna_expr
FIELDS TERMINATED BY ',' 
LINES TERMINATED BY '\n' 
IGNORE 1 LINES;

SELECT id, average FROM mirna_expr
INTO OUTFILE '/usr/local/dbOutput/mirna.csv'
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n';
